@baseUrl = http://localhost:3000/api
@productId = 2

### Criar produto base (se necessário)
POST {{baseUrl}}/products
Content-Type: application/json

{
  "sku": "ABC123",
  "name": "Sela padrão",
  "price": "199.90",
  "quantity": 10
}

### Conferir antes da entrada
GET {{baseUrl}}/products/{{productId}}

### Entrada de estoque (+5)
PATCH {{baseUrl}}/products/{{productId}}/in
Content-Type: application/json

{
  "qty": 5
}

### Conferir após a entrada
GET {{baseUrl}}/products/{{productId}}

### Listar produtos
GET {{baseUrl}}/products

### Atualizar produto
PATCH {{baseUrl}}/products/{{productId}}
Content-Type: application/json

{
  "price": "209.90",
  "quantity": 15
}

### Remover produto
DELETE {{baseUrl}}/products/{{productId}}
